### ISSUE TITLE
What is the best way to manage an https proxy

### ISSUE THREAD

**Issue by bw-theo-omtzigt** [h2non/toxy#33]
In the rocky documentation, the use of a TOML file is presented. 

What is the best way to install and manage a self-signed cert for a toxy-based HTTPS proxy?

**Comment by h2non** [comment]
You can do it programatically. You can see an example [here](https://github.com/h2non/toxy/blob/master/examples/https.js).

**Comment by bw-theo-omtzigt** [comment]
I was able to get the example to proxy httpbin.org. I am trying to proxy s3.amazonaws.com with this code:

var fs = require('fs')
var toxy = require('toxy')

var opts = {
  ssl: {
    key: fs.readFileSync('server.key', 'utf8'),
    cert: fs.readFileSync('server.crt', 'utf8')
  }
}

var proxy = toxy(opts)

// Forward to HTTPS server
proxy
  .get('/*')
  .option({ secure: false })
  .host('s3.amazonaws.com')
  .forward('https://s3.amazonaws.com')

proxy.listen(443)
console.log('HTTPS toxy-proxy listening on port: ', 443)


but then run into this problem (my .boto redirects to localhost and 443)
python s3-boto-test.py 
Traceback (most recent call last):
  File "s3-boto-test.py", line 7, in <module>
    b = conn.create_bucket(bucket_name)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
    data=data)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 913, in _mexe
    self.is_secure)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 705, in get_http_connection
    return self.new_http_connection(host, port, is_secure)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 747, in new_http_connection
    connection = self.proxy_ssl(host, is_secure and 443 or 80)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 792, in proxy_ssl
    int(self.proxy_port)), timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 61] Connection refused

I don't understand the option yet, so will permutate that in the mean time.

**Comment by h2non** [comment]
Seems like the server is replying with a `Location` header. I would recommend you to test it directly from another HTTP client (like your browser) in order to determine where is the origin of the issue.

**Comment by h2non** [comment]
Closing for now due to inactivity.

**Comment by rcsavage** [comment]
I am seeing this error too, don't close.

**Comment by SPSpwetter** [comment]
@h2non is saying that you should see if the browser can connect to the server without toxy, as the server may be the problem, not toxy. In other words, eliminate other possible contributing factors.
