### ISSUE TITLE
lib/helpers/each-series.js:2 TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by derFunk** [h2non/toxy#34]
Just happened after using Toxy (installed via current npm) on a random website:

> Server listening on port: 3000
/node_modules/toxy/lib/helpers/each-series.js:2
  var stack = arr.slice()
                 ^
TypeError: Cannot read property 'slice' of null
    at Object.eachSeries (/node_modules/toxy/lib/helpers/each-series.js:2:18)
    at ServerResponse.res.end (/node_modules/toxy/lib/poisons/throttle.js:33:15)
    at end \[as _onTimeout\] (/node_modules/toxy/lib/poisons/slow-close.js:40:17)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by h2non** [comment]
This should be fixed now. Just update `toxy`:
```bash
npm i toxy --force
```

Thank you for reporting.
